#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_LD, DIR_RD, DIR_END };

enum OBJID { OBJ_PLAYER, OBJ_BLADE, OBJ_BLOCK, OBJ_MONSTER, OBJ_MOUSE, OBJ_BUTTON, OBJ_END };

enum SCENEID { SC_MENU, SC_FIELD, SC_ENDING, SC_EDIT, SC_END };